# Generated by Django 3.1.14 on 2025-01-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreportdata',
            name='reported_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userreportdata',
            name='reported_threads',
            field=models.IntegerField(default=0),
        ),
    ]
