# Generated by Django 3.0 on 2025-01-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.CharField(choices=[('national_certificate', '国家資格'), ('vendor_certificate', 'ベンダー資格'), ('programming_language', 'プログラミング言語'), ('software', 'ソフトウェア'), ('hardware', 'ハードウェア'), ('database', 'データベース'), ('network', 'ネットワーク'), ('security', 'セキュリティ')], max_length=50),
        ),
    ]
