# Generated by Django 3.0 on 2025-01-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250111_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_reported',
        ),
    ]
